version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - arrayable
  - arrayify
  - boolable
  - boolify
  - floatify
  - intable
  - integerable
  - integerify
  - typeas
  - unboolable
  - unfloatable
  - unintegerable
  - unstringable
import: []
